---
namespace: myllynen
name: rhel_image
version: "1.0.3"
readme: README.md
authors:
  - Marko Myllynen <myllynen@redhat.com>
description: >
  Ansible role for building RHEL images with Image Builder.
license:
  - GPL-3.0-or-later
tags:
  - imagebuilder
  - build
  - image
  - linux
  - rhel
  - edge
  - tools
  - infrastructure
dependencies: {}
repository: https://www.github.com/myllynen/rhel-image
issues: https://www.github.com/myllynen/rhel-image/issues
