---
- name: Build RHEL image with Image Builder
  hosts: all
  become: true
  vars:
    rhel_image_update_host: false
    rhel_image_create_user: false

    rhel_image_git_remote_repo: file:///tmp/rhel-image-blueprints.git
    rhel_image_git_repo_checkout: master
    rhel_image_blueprint: base-image
    rhel_image_output_type: qcow2
    # NB. This is in MiB
    rhel_image_size: 30720
    # Optional image filename to use instead of UUID
    #rhel_image_filename: ci-daily-image.qcow2

    # This is on the build host
    rhel_image_download_dir: /tmp/images
    # Fetch from the build host
    rhel_image_fetch_image: true
    # This is where this playbook runs
    rhel_image_fetch_directory: /tmp
    rhel_image_remote_delete: true
  roles:
    - myllynen.rhel_image.rhel_image
